/*
 * Messages API
 *
 * The Messaging API is a new API that consolidates all messaging channels. It encapsulates a user (developer) from having to use multiple APIs to interact with our various channels such as SMS, MMS, Viber, Facebook Messenger, etc. The API normalises information across all channels to abstracted to, from and content. This API is currently Beta.
 *
 * API version: 0.3.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InboundMessageMessageContent struct {
	// The type of message being received.
	Type string `json:"type,omitempty"`
	// The body of the message.
	Text string `json:"text,omitempty"`
	Image ImageProperty `json:"image,omitempty"`
	Audio AudioProperty `json:"audio,omitempty"`
	Video VideoProperty `json:"video,omitempty"`
	File FileProperty `json:"file,omitempty"`
	Location LocationProperty `json:"location,omitempty"`
}
