/*
 * Messages API
 *
 * The Messaging API is a new API that consolidates all messaging channels. It encapsulates a user (developer) from having to use multiple APIs to interact with our various channels such as SMS, MMS, Viber, Facebook Messenger, etc. The API normalises information across all channels to abstracted to, from and content. This API is currently Beta.
 *
 * API version: 0.3.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MessageStatus struct {
	// The UUID of the message.
	MessageUuid string `json:"message_uuid"`
	To ToProperty `json:"to"`
	From FromProperty `json:"from"`
	// The datetime of when the event occurred.
	Timestamp string `json:"timestamp"`
	// The status of the message. The `read` message status is only available for `messenger` and `whatsapp`.
	Status string `json:"status"`
	Error MessageStatusError `json:"error,omitempty"`
	Usage MessageStatusUsage `json:"usage,omitempty"`
	// The client's reference.
	ClientRef string `json:"client_ref,omitempty"`
}
