/*
 * Messages API
 *
 * The Messaging API is a new API that consolidates all messaging channels. It encapsulates a user (developer) from having to use multiple APIs to interact with our various channels such as SMS, MMS, Viber, Facebook Messenger, etc. The API normalises information across all channels to abstracted to, from and content. This API is currently Beta.
 *
 * API version: 0.3.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NewMessage struct {
	To ToProperty `json:"to"`
	From FromProperty `json:"from"`
	Message MessageProperty `json:"message"`
	// Client reference of up to 40 characters. The reference will be present in every message status.
	ClientRef string `json:"client_ref,omitempty"`
}
