/*
 * Messages API
 *
 * The Messaging API is a new API that consolidates all messaging channels. It encapsulates a user (developer) from having to use multiple APIs to interact with our various channels such as SMS, MMS, Viber, Facebook Messenger, etc. The API normalises information across all channels to abstracted to, from and content. This API is currently Beta.
 *
 * API version: 0.3.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ToProperty struct {
	// The type of message that you want to send.
	Type string `json:"type"`
	// **Messenger**: The ID of the message recipient. This value should be the `from.id` value you received in the inbound messenger event. 
	Id string `json:"id,omitempty"`
	// **SMS**, **Viber**, **WhatsApp** or **MMS**:  The phone number of the message recipient in the [E.164](https://en.wikipedia.org/wiki/E.164) format. Don't use a leading + or 00 when entering a phone number, start with the country code, for example, 447700900000. 
	Number string `json:"number,omitempty"`
}
