/*
 * Messages API
 *
 * The Messaging API is a new API that consolidates all messaging channels. It encapsulates a user (developer) from having to use multiple APIs to interact with our various channels such as SMS, MMS, Viber, Facebook Messenger, etc. The API normalises information across all channels to abstracted to, from and content. This API is currently Beta.
 *
 * API version: 0.3.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The error format is standardized to the 4xx/5xx range with a code and a human readable explanation.
type Error struct {
	Type string `json:"type"`
	Title string `json:"title"`
	Detail string `json:"detail"`
	Instance string `json:"instance"`
}
